spring.application.name=LEARNING_JPA

spring.datasource.url=jdbc:postgresql://localhost:5433/postgres?options=-c%20TimeZone=Asia/Kathmandu
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database=postgresql
spring.jpa.show-sql=true